# =============================================
# PROD PROFILE -  Deployment hugging space 
# =============================================
# Server
server.port=${PORT:7860}
server.servlet.context-path=/api/v1

# Database - Neon PostgreSQL (env vars)
spring.datasource.name=neondb
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# HikariCP - optimized for Neon scale-to-zero
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_batch_fetch_size=20

# Logging
logging.level.com.examplatform=INFO
logging.level.org.springframework.web=WARN

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Multipart
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Jackson
spring.jackson.time-zone=Asia/Dhaka
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Pagination
app.pagination.default-page-size=20
app.pagination.max-page-size=100

# Groq API
groq.api.key=${GROQ_API_KEY:test-key}


# Gemini API
# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.model=${GEMINI_MODEL:gemini-2.5-flash}
# Actuator - disable DB health check to avoid constant DB pings
management.health.db.enabled=false
